"""
Assumption engine — turns a classified company into a full forecast.

Produces, for the base case:
  * a revenue-growth path that fades from today's growth toward a terminal rate,
  * an operating-margin path that converges from today's margin to a sustainable
    target (this is what lets us value turnarounds AND pre-profit cash-burners:
    margins ramp from where they are to where the business should mature),
  * a reinvestment intensity (sales-to-capital) that ties growth to the capital
    needed to fund it,
  * a terminal growth rate capped at the risk-free rate.

Scenarios and Monte Carlo are generated by shifting these base drivers.
"""
from __future__ import annotations

from dataclasses import dataclass, field, replace
from statistics import median
from typing import Optional

from ..data.models import CompanyData
from .classify import Classification

# Sustainable operating-margin anchors by sector (used when a company has no
# usable margin history, e.g. a pre-profit growth name).
SECTOR_TARGET_MARGIN = {
    "Technology": 0.27, "Communication Services": 0.20, "Consumer Cyclical": 0.10,
    "Consumer Defensive": 0.13, "Healthcare": 0.18, "Industrials": 0.13,
    "Energy": 0.12, "Basic Materials": 0.12, "Utilities": 0.16,
    "Real Estate": 0.22, "Financial Services": 0.25,
}
# Capital efficiency (ΔRevenue per $1 reinvested) by sector.
SECTOR_SALES_TO_CAPITAL = {
    "Technology": 2.8, "Communication Services": 2.0, "Consumer Cyclical": 2.0,
    "Consumer Defensive": 1.8, "Healthcare": 2.2, "Industrials": 1.5,
    "Energy": 1.0, "Basic Materials": 1.0, "Utilities": 0.6, "Real Estate": 0.7,
    "Financial Services": 3.0,
}
N_YEARS_BY_REGIME = {"mature": 5, "cyclical": 5, "growth": 7, "hypergrowth": 10, "financial": 5}
GROWTH_CAP_BY_REGIME = {"mature": 0.15, "cyclical": 0.12, "growth": 0.35,
                        "hypergrowth": 0.60, "financial": 0.15}
PLATEAU_BY_REGIME = {"mature": 0, "cyclical": 0, "growth": 1, "hypergrowth": 2, "financial": 0}


def _clamp(x, lo, hi):
    return max(lo, min(hi, x))


@dataclass
class AssumptionSet:
    label: str
    n_years: int
    base_revenue: float
    rev_growth_path: list       # length n_years
    op_margin_path: list        # length n_years
    terminal_growth: float
    sales_to_capital: float
    tax_rate: float
    # transparency
    start_growth: float
    current_margin: float
    target_margin: float
    notes: list = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "label": self.label, "n_years": self.n_years, "base_revenue": self.base_revenue,
            "rev_growth_path": self.rev_growth_path, "op_margin_path": self.op_margin_path,
            "terminal_growth": self.terminal_growth, "sales_to_capital": self.sales_to_capital,
            "tax_rate": self.tax_rate, "start_growth": self.start_growth,
            "current_margin": self.current_margin, "target_margin": self.target_margin,
            "notes": self.notes,
        }


def _fade_path(g0: float, g_term: float, n: int, plateau: int) -> list:
    """Hold g0 for `plateau` years, then linearly fade to g_term by year n."""
    path = []
    for t in range(1, n + 1):
        if t <= plateau:
            path.append(g0)
        else:
            # linear fade over the remaining years, ending exactly at g_term
            span = n - plateau
            step = (t - plateau) / span
            path.append(g0 + (g_term - g0) * step)
    return path


def _margin_path(m0: float, m_target: float, n: int) -> list:
    """Linear convergence from current margin to the target by year n."""
    return [m0 + (m_target - m0) * (t / n) for t in range(1, n + 1)]


def _target_margin(cd: CompanyData, cls: Classification, current: float) -> float:
    gm = cd.gross_margin
    sector_t = SECTOR_TARGET_MARGIN.get(cd.sector, 0.12)
    hist_pos = [m for m in (cd.ebit_margin_history or []) if m and m > 0]
    hist_ref = median(hist_pos) if hist_pos else None

    if cls.regime == "hypergrowth" and (current is None or current < 0.05):
        target = sector_t  # path to sector-normal profitability
    elif cls.regime == "cyclical":
        target = hist_ref if hist_ref is not None else sector_t  # mid-cycle
    else:
        base_ref = current if current is not None else sector_t
        target = max(base_ref, hist_ref if hist_ref is not None else base_ref)
        if cls.regime == "growth" and sector_t > target:
            target = 0.5 * target + 0.5 * sector_t  # scaling into margin

    # Caps: can't exceed ~85% of gross margin, absolute sanity cap, and a floor.
    if gm is not None and gm > 0:
        target = min(target, gm * 0.85)
    return _clamp(target, 0.03, 0.45)


def _sales_to_capital(cd: CompanyData) -> float:
    stc = SECTOR_SALES_TO_CAPITAL.get(cd.sector, 1.8)
    # Nudge by observed capital intensity.
    if cd.revenue and cd.capex is not None and cd.revenue > 0:
        intensity = cd.capex / cd.revenue
        if intensity < 0.03:
            stc *= 1.25
        elif intensity > 0.10:
            stc *= 0.75
    return _clamp(stc, 0.5, 4.0)


def build_base_assumptions(cd: CompanyData, cls: Classification, rf: float, cfg) -> AssumptionSet:
    notes = []
    n = N_YEARS_BY_REGIME.get(cls.regime, 5)

    base_rev = cd.revenue if cd.revenue else 0.0

    # Current operating margin (fallbacks keep it finite).
    current = cd.ebit_margin
    if current is None and cd.net_margin is not None:
        current = cd.net_margin / 0.75  # rough gross-up from net to operating
    if current is None:
        current = SECTOR_TARGET_MARGIN.get(cd.sector, 0.10)
        notes.append("No operating margin available; assumed sector-normal current margin.")
    current = _clamp(current, -0.50, 0.60)

    target = _target_margin(cd, cls, current)

    # Start growth.
    g0 = cls.blended_growth if cls.blended_growth is not None else 0.05
    g0 = _clamp(g0, -0.15, GROWTH_CAP_BY_REGIME.get(cls.regime, 0.15))

    # Terminal growth: capped at the risk-free rate (perpetuity can't outgrow econ).
    g_term = max(0.015, min(cfg.terminal_growth_cap, rf if rf else cfg.terminal_growth_cap))

    growth_path = _fade_path(g0, g_term, n, PLATEAU_BY_REGIME.get(cls.regime, 0))
    margin_path = _margin_path(current, target, n)
    stc = _sales_to_capital(cd)
    tax = cfg.marginal_tax_rate

    if cls.regime == "hypergrowth":
        notes.append(f"Long {n}-yr forecast; margins ramp {current:.0%}→{target:.0%} "
                     f"(path to profitability); growth fades {g0:.0%}→{g_term:.1%}.")
    elif current < target - 0.01:
        notes.append(f"Turnaround/expansion: operating margin recovers {current:.0%}→{target:.0%}.")
    else:
        notes.append(f"Margin held near {target:.0%}; growth fades {g0:.0%}→{g_term:.1%} over {n} yrs.")

    return AssumptionSet(
        label="base", n_years=n, base_revenue=base_rev, rev_growth_path=growth_path,
        op_margin_path=margin_path, terminal_growth=g_term, sales_to_capital=stc,
        tax_rate=tax, start_growth=g0, current_margin=current, target_margin=target, notes=notes,
    )


def apply_overrides(base: AssumptionSet, cls: Classification, overrides: dict) -> AssumptionSet:
    """Rebuild the base assumptions with user-supplied overrides from the UI.

    Recognized keys: start_growth, target_margin, terminal_growth, n_years,
    sales_to_capital, tax_rate. Paths are regenerated so a tweak to (say) the
    target margin flows through the whole forecast.
    """
    if not overrides:
        return base
    n = int(overrides.get("n_years", base.n_years))
    n = max(3, min(15, n))
    start_g = float(overrides.get("start_growth", base.start_growth))
    term_g = float(overrides.get("terminal_growth", base.terminal_growth))
    term_g = _clamp(term_g, 0.0, 0.05)
    target_m = float(overrides.get("target_margin", base.target_margin))
    stc = float(overrides.get("sales_to_capital", base.sales_to_capital))
    tax = float(overrides.get("tax_rate", base.tax_rate))
    plateau = PLATEAU_BY_REGIME.get(cls.regime, 0)

    growth_path = _fade_path(start_g, term_g, n, min(plateau, n - 1))
    margin_path = _margin_path(base.current_margin, target_m, n)
    notes = list(base.notes) + ["Assumptions overridden in the UI."]
    return AssumptionSet(
        label="base", n_years=n, base_revenue=base.base_revenue, rev_growth_path=growth_path,
        op_margin_path=margin_path, terminal_growth=term_g, sales_to_capital=_clamp(stc, 0.4, 5.0),
        tax_rate=_clamp(tax, 0.0, 0.45), start_growth=start_g, current_margin=base.current_margin,
        target_margin=target_m, notes=notes,
    )


def shift_assumptions(base: AssumptionSet, growth_delta=0.0, margin_delta=0.0,
                      term_delta=0.0, stc_mult=1.0, label=None) -> AssumptionSet:
    """Return a copy of `base` with drivers shifted (for scenarios / MC / reverse DCF)."""
    new_growth = [g + growth_delta for g in base.rev_growth_path]
    new_margin = [_clamp(m + margin_delta, -0.60, 0.60) for m in base.op_margin_path]
    new_term = max(0.005, min(base.terminal_growth + term_delta, 0.05))
    return replace(
        base,
        label=label or base.label,
        rev_growth_path=new_growth,
        op_margin_path=new_margin,
        terminal_growth=new_term,
        sales_to_capital=_clamp(base.sales_to_capital * stc_mult, 0.4, 5.0),
        start_growth=base.start_growth + growth_delta,
        target_margin=_clamp(base.target_margin + margin_delta, 0.02, 0.55),
    )
