# -*- coding: utf-8 -*-
"""ITEM 18 — the Index's backtest is the SERVED book's, and its figures cannot go stale silently.

WHAT THIS GUARDS
----------------
`index_book_measured` holds committed literals, which is the family that produced E9 and E12 one
session ago. The difference, and the reason these tests exist: a stale-literal defect is a figure
that tracks a CLOCK — a trial count, a universe size, a date — and no test can pin it. These
track a dated STUDY with a committed artifact, so they CAN be pinned, against the record itself.

`TheConstantsMatchTheCommittedRecord` asserts every figure appears verbatim in BOTH
`HANDOFF_edge_audit.md` and `VALQUO_LEDGER.md`. Re-run `INDEX-BOOK` and the record moves; the
record moving turns this suite red and the module has to be updated with it. That is `MA13`'s
committed-literal idiom: the human record and the machine record are the same bytes.

THE BUILD PATH IS NOT TOUCHED, AND IT IS PROVED RATHER THAN PROMISED
--------------------------------------------------------------------
Item 18 forbids changing how a rebalance book is BUILT. `headline_scope` is a disclosure field,
so `TheDisclosureIsInertOnTheBook` runs `build_index` against the pre-change source restored from
git and requires every field a book consists of to be identical across both arms — and PRINTS the
counts, because the first cut of that proof built from the local store's ONE-NAME fixture and
"nothing moved" meant almost nothing. A proof with no reach is the vacuous-pass family.
"""
import importlib
import io
import json
import os
import subprocess
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import tests.state_isolation  # noqa: F401,E402

from valuation.screener import index_book_measured as M      # noqa: E402

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HANDOFF = os.path.join(REPO, "HANDOFF_edge_audit.md")
LEDGER = os.path.join(REPO, "VALQUO_LEDGER.md")
#: ITEM 47: the GENERATED old-to-new figure table, which is the binding record for every
#: figure the canonical move restated.
TABLE = os.path.join(REPO, "CANONICAL_FIGURE_TABLE.md")
VI = os.path.join(REPO, "valuation", "edge", "valquo_index.py")


def _read(p):
    with io.open(p, encoding="utf-8") as f:
        return f.read()


def _norm(s):
    """Typographic minus and en-dash normalised to ASCII. A test comparing a NUMBER in prose
    must compare the number and not the glyph — the first cut of the spec test failed on
    `-0.0576` because the record writes it with U+2212."""
    return s.replace("−", "-").replace("–", "-")


class TheConstantsMatchTheCommittedRecord(unittest.TestCase):
    """The anti-stale guard. Both inputs are tracked, so this runs on a CI runner."""

    #: Every figure the module publishes: the constant, the spelling a TRACKED record uses,
    #: and the scale that turns one into the other (the figure table states fractions, the
    #: module publishes percent).
    #:
    #: RESTATED 2026-10-10 BY THE CANONICAL MOVE, AND THE BINDING RECORD CHANGED WITH IT.
    #: `CANONICAL_FIGURE_TABLE.md` is tracked and GENERATED by `scripts/canon_figure_table.py`
    #: from the landed artifacts, so it is written by the measurement rather than by the page
    #: -- which is the property `MA13`'s idiom needs and which a hand-written handoff section
    #: only approximates. Re-run the study, the table moves, this suite goes red.
    #:
    #: WHAT IS NOT IN THE TABLE IS NOT PUBLISHED. Seven of the module's figures are pinned in
    #: `HANDOFF_edge_audit.md`'s own corrected table as well, and those are listed too. The
    #: figures r1 measured but never published -- the half-sample splits, the tracking error,
    #: the months-to-detect, the research arm's seven -- are REPORTED ABSENT by the module
    #: rather than carried as literals nothing pins. `test_nothing_unpinned_is_published`
    #: below is what keeps that honest.
    FIGURES = (
        # (constant, text, scale, record)   record: "T" = figure table, "H" = handoff
        ("SERVED_ROTH_PCT", "18.0169", 1.0, "H"),
        ("SERVED_TAXABLE_PCT", "12.5036", 1.0, "H"),
        ("SERVED_ROTH_SHARPE", "0.9694", 1.0, "H"),
        ("SERVED_ROTH_MAXDD_PCT", "-28.96", 1.0, "H"),
        ("ALPHA_VS_OWN_TIER_PP", "4.6177", 1.0, "H"),
        ("SERVED_NET_PCT", "0.180403", 100.0, "T"),
        ("SERVED_SHARPE", "0.969432", 1.0, "T"),
        ("SERVED_MAXDD_PCT", "-0.289973", 100.0, "T"),
        ("SERVED_TURNOVER", "2.809390", 1.0, "T"),
        ("SERVED_COST_BPS_ONE_WAY", "9.435593", 1.0, "T"),
        ("SPY_PCT", "0.158226", 100.0, "T"),
        ("ALL_CAP_EW_PCT", "0.121116", 100.0, "T"),
        ("ALPHA_VS_SPY_PP", "0.022177", 100.0, "T"),
        ("ALPHA_VS_ALL_CAP_EW_PP", "0.059288", 100.0, "T"),
        # The previous panel's figures, kept so the restatement is legible. Same records.
        ("ALPHA_VS_ALL_CAP_EW_PUBLISHED_PP", "-0.000576", 100.0, "T"),
        ("ALL_CAP_EW_PUBLISHED_PCT", "0.172393", 100.0, "T"),
        ("SERVED_NET_PUBLISHED_PCT", "0.171817", 100.0, "T"),
        # The signed contract's own trio. NOT restated -- see the module.
        ("CONTRACT_SIGNED_ALPHA_VS_SPY_PP", "1.9488", 1.0, "H"),
        ("CONTRACT_SIGNED_TE_VS_SPY", "8.4381", 1.0, "H"),
        ("CONTRACT_EDGE_IN_USE_PP", "9.9864", 1.0, "H"),
    )

    #: DERIVED, never a literal (`B7`): both reproduce the artifact exactly.
    DERIVED = (("TIER_EW_PCT", 13.4226), ("TAX_COST_PP", 5.5133))

    def test_both_records_are_present(self):
        """A guard whose input is absent passes while checking nothing."""
        self.assertTrue(os.path.exists(HANDOFF))
        self.assertTrue(os.path.exists(LEDGER))
        self.assertTrue(os.path.exists(TABLE), "the generated figure table is missing")

    def test_every_constant_is_the_value_the_module_declares(self):
        """The literal in the table above must equal the module's own constant, or this suite
        is checking the table against the record and never the code."""
        for name, text, scale, _rec in self.FIGURES:
            self.assertAlmostEqual(getattr(M, name), float(text) * scale, places=4,
                                   msg="%s does not equal %s x %s" % (name, text, scale))

    def test_every_figure_appears_in_its_named_record(self):
        """Each figure is checked against the record that actually carries it.

        The FIGURE TABLE is generated from the artifacts; the HANDOFF is r1's write-up. Both
        are tracked, so both run on a CI runner, and naming which one per figure is what stops
        this from degrading into "the number is somewhere in the repo".
        """
        docs = {"T": _norm(_read(TABLE)), "H": _norm(_read(HANDOFF))}
        for name, text, _scale, rec in self.FIGURES:
            self.assertIn(text, docs[rec],
                          "%s (%s) is not in %s" % (name, text,
                                                    "CANONICAL_FIGURE_TABLE.md" if rec == "T"
                                                    else "HANDOFF_edge_audit.md"))

    def test_the_generated_table_is_the_binding_record_and_is_not_hand_written(self):
        """The property that makes the pin worth anything: the table says so itself, and the
        script that writes it exists."""
        t = _read(TABLE)
        self.assertIn("Generated by `scripts/canon_figure_table.py`", t)
        self.assertIn("do not hand-edit", t)
        self.assertTrue(os.path.exists(os.path.join(REPO, "scripts", "canon_figure_table.py")))

    def test_the_derived_figures_are_derived_and_reproduce_the_artifact(self):
        """`B7`: one definition. The tier benchmark's level and the tax cost are differences
        of figures already published, so they are computed rather than typed -- and they must
        come out at the artifact's own values, which is the check that the arithmetic is the
        right arithmetic and not merely self-consistent."""
        for name, want in self.DERIVED:
            self.assertAlmostEqual(getattr(M, name), want, places=4)
        src = _read(os.path.join(REPO, "valuation", "screener", "index_book_measured.py"))
        for name, _want in self.DERIVED:
            line = next(l for l in src.split("\n") if l.startswith(name + " ="))
            self.assertIn("round(", line, "%s is a literal; it must be derived" % name)

    def test_nothing_unpinned_is_published(self):
        """THE RULE THE RESTATEMENT TURNS ON, asserted rather than trusted.

        r1 measured far more than it published. Every figure this module ships has to be in a
        tracked record; everything else is reported as `None` with a reason. So any numeric
        constant the module exposes must appear in `FIGURES` or `DERIVED` -- a new literal
        appearing here, pinned to nothing, is what this catches.
        """
        pinned = {n for n, _t, _s, _r in self.FIGURES} | {n for n, _w in self.DERIVED}
        allowed = pinned | {
            "PANEL_SHARED_DATES", "CONTRACT_TE_IN_USE", "CONTRACT_MONTHS_IN_USE",
            "CONTRACT_SIGNED_MONTHS_TO_DETECT", "RESEARCH_ALPHA_VS_SPY_PP",
            "DECILE_NAMES_APPROX",
        }
        unpinned = []
        for name in dir(M):
            if name.startswith("_") or name in allowed:
                continue
            v = getattr(M, name)
            if isinstance(v, bool) or not isinstance(v, (int, float)):
                continue
            unpinned.append(name)
        self.assertEqual(unpinned, [],
                         "these numeric constants are published and pinned to no record: %r"
                         % (unpinned,))

    def test_the_figures_r1_did_not_publish_are_reported_ABSENT_not_carried(self):
        """`V6`'s rule: an absent measurement and a null must not read the same.

        The published module carried a taxable Sharpe, a tracking error, a months-to-detect
        and seven research-decile figures. None of their corrected values is in a tracked
        record, so the module reports them absent WITH A REASON rather than leaving the
        2,531-name panel's values on a page that now describes 9,645 names.
        """
        b = M.block()
        self.assertIsNone(b["taxable"]["sharpe"])
        self.assertIn("no tracked record", b["taxable"]["not_restated_reason"])
        self.assertIsNone(b["power"]["months_to_detect_vs_spy"])
        self.assertIsNone(b["power"]["own_tracking_error_pp"])
        self.assertIn("MB8", b["power"]["not_restated_reason"])
        r = M.research_block()
        for k in ("net_pct", "alpha_vs_ew_pp", "sharpe", "annual_turnover",
                  "months_to_detect_vs_spy"):
            self.assertIsNone(r[k], "%s is published without a record to pin it" % k)
        self.assertIn("no tracked record", r["not_restated_reason"])
        # And the one figure Don's ruling DOES name is present and negative.
        self.assertLess(r["net_alpha_vs_spy_pp"], 0.0)
        self.assertIn("does NOT beat SPY", r["net_alpha_vs_spy_sentence"])

    def test_the_provenance_resolves_to_a_REAL_commit_that_names_the_study(self):
        """Checked against GIT rather than against the markdown, which is where it belongs:
        neither the ledger nor the handoff records the sha, so asserting it appears in them
        fails against a correct tree. Git is the authority on whether a commit exists."""
        self.assertEqual(M.STUDY, "INDEX-BOOK")
        self.assertTrue(M.STUDY_COMMIT)
        r = subprocess.run(["git", "log", "-1", "--format=%s", M.STUDY_COMMIT],
                           cwd=REPO, capture_output=True)
        if r.returncode != 0:
            self.skipTest("commit %s not reachable in this checkout" % M.STUDY_COMMIT)
        subject = r.stdout.decode("utf-8", "replace")
        self.assertIn("INDEX-BOOK", subject,
                      "%s is not the study's commit: %r" % (M.STUDY_COMMIT, subject))

    def test_the_study_has_a_record_row_at_all(self):
        self.assertIn("INDEX-BOOK", _read(LEDGER))
        self.assertIn("INDEX-BOOK", _read(HANDOFF))


class TheTwoBenchmarksAreLikeForLikeAndTheDroppedOneIsExplained(unittest.TestCase):
    """DON'S 2026-10-10 RULING, AND IT REPLACES `INDEX-BOOK`'s VOID CONDITION.

    That register's rule was that both alpha sentences travel together: against its own tier
    the book earned +4.1209pp and against the all-cap equal-weighted universe -0.0576pp, so
    quoting the first alone misled and `block()` refused to emit one without the other.

    ON THE CORRECTED UNIVERSE THAT GUARD INVERTS. The all-cap leg reads +5.9288pp -- and
    r1 measured that the move is mostly the BENCHMARK FALLING (17.2393% -> 12.1116%/yr) rather
    than the Index rising (17.1817% -> 18.0403%). A guard that forced the pairing would now be
    forcing the flattering number onto the page, which is the opposite of what it was for.

    Don ruled the all-cap leg OFF the tab, with the Index shown against SPY and against an
    equal-weighted basket of its own $10B tier -- like for like -- and its return, drawdown and
    Sharpe beside them. These tests assert that, and they assert the dropped comparison is
    EXPLAINED rather than silently removed.
    """

    def test_the_all_cap_leg_is_off_the_card(self):
        keys = {l.get("key") for l in M.card()["lines"]}
        self.assertNotIn("vs_all_cap_ew", keys,
                         "the all-cap comparison is still rendered; Don ruled it off the tab")

    def test_the_two_like_for_like_legs_ARE_on_the_card(self):
        keys = {l.get("key") for l in M.card()["lines"]}
        self.assertIn("vs_own_tier", keys)
        self.assertIn("vs_spy", keys)

    def test_the_rulings_four_other_figures_are_beside_them(self):
        """"with its return, drawdown and Sharpe beside them" -- and both benchmark LEVELS, so
        a reader can see what the benchmark did rather than only the difference."""
        c = M.card()
        self.assertIsNotNone(c["sharpe"])
        self.assertIsNotNone(c["max_drawdown_pct"])
        keys = {l.get("key") for l in c["lines"]}
        for k in ("roth", "bench_spy", "bench_tier"):
            self.assertIn(k, keys, "%s is not on the card" % k)

    def test_the_dropped_leg_is_EXPLAINED_and_still_in_the_payload(self):
        """Deleting it would make the correction invisible instead of explained. A reader who
        finds +5.93pp in r1's table must be able to find out why it is not on the page."""
        a = M.block()["alpha"]
        self.assertAlmostEqual(a["vs_all_cap_ew_pp"], 5.9288, places=4)
        self.assertFalse(a["vs_all_cap_ew_shown_on_the_tab"])
        note = a["vs_all_cap_ew_note"]
        for text in ("%.4f" % M.ALPHA_VS_ALL_CAP_EW_PP,
                     "%.4f" % M.ALPHA_VS_ALL_CAP_EW_PUBLISHED_PP,
                     "%.4f" % M.ALL_CAP_EW_PUBLISHED_PCT, "%.4f" % M.ALL_CAP_EW_PCT):
            self.assertIn(text, note, "the explanation omits %s" % text)
        self.assertIn("BENCHMARK FALLING", note)
        self.assertIn("2026-10-10", note, "the note does not say whose ruling it is")

    def test_the_explanation_reaches_the_card_and_the_tab(self):
        self.assertEqual(M.card()["all_cap_note"], M.all_cap_leg_note())
        js = _read(os.path.join(REPO, "valuation", "web", "static", "app.js"))
        self.assertIn("bc.all_cap_note", js, "the tab never renders the explanation")

    def test_the_sentence_names_both_benchmarks_and_their_levels(self):
        s = M.block()["alpha"]["both_sentence"]
        for text in ("%.4f" % M.ALPHA_VS_OWN_TIER_PP, "%.4f" % M.ALPHA_VS_SPY_PP,
                     "%.4f" % M.TIER_EW_PCT, "%.4f" % M.SPY_PCT):
            self.assertIn(text, s)
        self.assertIn("like for like", s)

    def test_the_tier_benchmark_is_NOT_the_all_cap_one(self):
        """The whole reason the two legs differ. If these ever coincide the tab is showing one
        benchmark twice under two names."""
        self.assertNotAlmostEqual(M.TIER_EW_PCT, M.ALL_CAP_EW_PCT, places=2)

    def test_the_halves_are_reported_as_NOT_restated_rather_than_carried(self):
        note = M.block()["alpha"]["halves_not_restated"]
        self.assertIn("NOT restated", note)
        self.assertIn("3.7202", note, "the published halves are not named, so a reader cannot "
                                      "tell what was dropped")
        self.assertIn("may not be quoted", note)


class ThePowerStatementIsHonest(unittest.TestCase):
    """REPOINTED BY ITEM 47: the CONCLUSION is pinned, the arithmetic is reported absent.

    The published sentence quoted 4,383 months at the served book's own 8.4381pp tracking
    error. The corrected run measures both again and NEITHER is in a tracked record, so
    carrying them would be two literals pinned to nothing -- and `MB8` forbids filling the gap
    with the all-cap decile's tracking error, which is the one that IS published.

    What must survive is the protective half: that the forward test cannot settle whether the
    Index beats SPY. That is asserted; a month count is not.
    """

    def test_it_states_what_the_test_CANNOT_show(self):
        s = M.power_sentence()
        self.assertIn("cannot", s)
        self.assertIn("beats SPY", s)
        self.assertIn("CENTURIES", s)

    def test_it_states_what_the_test_CAN_show(self):
        s = M.power_sentence()
        self.assertIn("recorded honestly", s)
        self.assertIn("costs and turnover", s)

    def test_it_quotes_the_SERVED_books_own_edge_and_no_borrowed_tracking_error(self):
        """`MB8`: an `se` may not be borrowed across constructions. The sentence names the
        served book's own edge and names where the arithmetic lives; it must not reach for
        either tracking error the project has published."""
        s = M.power_sentence()
        self.assertIn("%.4f" % M.ALPHA_VS_SPY_PP, s)
        self.assertIn(M.CORRECTED_ARTIFACT, s)
        for borrowed in ("8.4381", "11.3878", "11.40", "4,383"):
            self.assertNotIn(borrowed, s,
                             "the sentence quotes %s, which is the previous panel's or another "
                             "book's" % borrowed)

    def test_the_power_block_says_the_arithmetic_is_absent_and_why(self):
        pw = M.block()["power"]
        self.assertIsNone(pw["months_to_detect_vs_spy"])
        self.assertIsNone(pw["own_tracking_error_pp"])
        self.assertIn("MB8", pw["not_restated_reason"])
        self.assertEqual(pw["sentence"], M.power_sentence())


class ThePowerStatementReachesThePageAndTheContractIsUntouched(unittest.TestCase):
    """Item 18: base the public power claim on the served book, and do NOT edit the signed
    contract -- draft the correction for the next amendment instead."""

    def test_the_tab_has_an_element_for_it(self):
        t = _read(os.path.join(REPO, "valuation", "web", "templates", "index.html"))
        self.assertIn('id="indexPowerNote"', t)

    def test_the_renderer_fills_it_from_the_SERVER_sentence(self):
        """Read on the code with comments stripped: a positive assertion satisfied by a
        comment goes green while the page stays blank."""
        import re
        src = _read(os.path.join(REPO, "valuation", "web", "static", "app.js"))
        src = re.sub(r"/\*.*?\*/", " ", src, flags=re.S)
        src = "\n".join(re.sub(r"//.*$", "", ln) for ln in src.splitlines())
        self.assertIn("indexPowerNote", src)
        self.assertIn("power", src)
        self.assertIn("pw.sentence", src,
                      "the note is not filled from the server's sentence")

    def test_a_null_gross_prints_only_the_net_figure(self):
        """FOUND BY MUTATION, which is why it is here: disabling the null-gross branch was
        NOT caught by anything. `INDEX-BOOK` measured the alpha legs NET and there is no gross
        figure for them, so printing "— gross · +4.12% net" puts an em dash where a reader
        reads a missing measurement rather than an absent concept."""
        import re
        src = _read(os.path.join(REPO, "valuation", "web", "static", "app.js"))
        src = re.sub(r"/\*.*?\*/", " ", src, flags=re.S)
        src = "\n".join(re.sub(r"//.*$", "", ln) for ln in src.splitlines())
        self.assertIn("l.gross == null", src,
                      "the renderer no longer special-cases a net-only card")
        # And the served card really does supply null grosses, or the branch is unreachable.
        grosses = [l.get("gross") for l in M.card()["lines"] if l.get("kind") == "excess"]
        self.assertTrue(grosses, "the served card has no excess lines")
        self.assertTrue(all(g is None for g in grosses),
                        "the served card invented a gross figure: %r" % (grosses,))

    def test_the_renderer_words_none_of_it(self):
        """One copy authority. If the page composed its own sentence, the page and the
        measurement could disagree about what five years can show."""
        import re
        src = _read(os.path.join(REPO, "valuation", "web", "static", "app.js"))
        src = re.sub(r"/\*.*?\*/", " ", src, flags=re.S)
        src = "\n".join(re.sub(r"//.*$", "", ln) for ln in src.splitlines())
        self.assertNotIn("4,383", src, "the renderer types a measured figure")
        self.assertNotIn("365 years", src)

    def test_the_SIGNED_contract_NOW_CARRIES_the_correction(self):
        """REPOINTED 2026-10-04: Don ACCEPTED the amendment, so this guard's premise inverted.

        It used to assert the opposite -- that the served figures appear in the DRAFT and
        NOWHERE in the contract -- and that was right while the correction was a proposal. The
        decision changed the fact, not the rule: the rule is that the contract and the
        measurement must agree, and before acceptance agreement meant the contract was silent.
        Now it means the contract states the figures.

        INVERTED RATHER THAN DELETED, because the direction is what carries the information: a
        test that merely checked "the figures are somewhere" would pass whether or not Don had
        ever decided anything.

        ASSERTED ON THE FILE'S CONTENT, NOT ON A DIFF -- kept from the original, and the reason
        is still good. My first cut ran `git diff origin/main -- PAPER_TRACK_CONTRACT.md`, and
        `test_ma60_conventions::NoSuiteAssertsOnAWorkingTreeDiff` refused it, rightly: that
        compares main against whatever is checked out, measures nothing about the lane that
        wrote it, and becomes a tripwire on a whole file that fires on the next unrelated lane.
        """
        contract = _norm(_read(os.path.join(REPO, "PAPER_TRACK_CONTRACT.md")))
        draft = _norm(_read(os.path.join(REPO, "PREREG_DRAFT_contract_amendment_2.md")))
        # SCOPED TO 2, AND MUTATION IS WHY. Asserting the figures appear ANYWHERE in the
        # contract passed against a mutant that changed 2's +1.9488 to +1.9000 -- because the
        # 5a-2 record quotes the same figure when it describes what part (b) did, so the guard
        # was satisfied by a sentence ABOUT the correction rather than by the correction. The
        # property is that 2's OWN arithmetic carries them.
        i = contract.index("## 2.")
        sec2 = contract[i:contract.index("## 3.", i)]
        self.assertIn("AMENDMENT 2", sec2, "2 does not reference the amendment at all")
        # ITEM 47: CHECKED AGAINST THE FIGURES THE CONTRACT WAS SIGNED WITH, not against the
        # module's live ones. The canonical move restated the served book on a 9,645-name
        # universe (+2.2177pp over SPY); `DECISIONS.md` 2026-10-07 is explicit that the move
        # does not touch the forward contract's frozen parameters, and the contract's own rule
        # forbids revising sigma downward -- a signed pre-registration whose numbers follow
        # the latest measurement is not one. So 2 keeps 1.9488 / 8.4381 / 4,383, and the
        # module carries them under `CONTRACT_SIGNED_*` so neither set can drift into the
        # other. Asserting the LIVE constants here would have demanded an edit to a signed
        # document.
        for text in ("%.4f" % M.CONTRACT_SIGNED_ALPHA_VS_SPY_PP,
                     "%.4f" % M.CONTRACT_SIGNED_TE_VS_SPY,
                     "{:,}".format(M.CONTRACT_SIGNED_MONTHS_TO_DETECT)):
            self.assertIn(text, draft, "the draft is missing %s" % text)
            self.assertIn(text, sec2,
                          "Amendment 2 was accepted on 2026-10-04, so PAPER_TRACK_CONTRACT.md "
                          "2 itself must carry %s -- see 5a-2 part (b)" % text)

    def test_the_amendment_is_recorded_as_ACCEPTED_and_in_the_amendment_form(self):
        """The acceptance has to be checkable from the contract alone, not from a commit
        message. 5a established the form: dated, attributed, nothing above it deleted."""
        contract = _norm(_read(os.path.join(REPO, "PAPER_TRACK_CONTRACT.md")))
        self.assertIn("5a-2. AMENDMENT 2", contract)
        self.assertIn("ACCEPTED BY DON on 2026-10-04", contract)
        self.assertIn("AMENDMENT 1", contract, "5a must not have been overwritten")

    def test_the_corporate_action_rule_is_in_the_contract_and_not_only_in_the_code(self):
        """Part (c), and it is the one part of Amendment 2 that governs a RECORDED NUMBER rather
        than a power calculation -- the engine has redistributed WBS's weight since 2026-07-30
        while the contract was silent. A rule the engine follows and the contract omits is a
        rule nobody can check the engine against."""
        contract = _norm(_read(os.path.join(REPO, "PAPER_TRACK_CONTRACT.md")))
        self.assertIn("SOLD AT ITS LAST TRADED CLOSE", contract)
        self.assertIn("REDISTRIBUTED PRO-RATA", contract)

    def test_sigma_is_still_11_40_and_was_not_lowered_by_the_amendment(self):
        """The one thing 6.5 forbids outright, and the thing an amendment about power is most
        likely to have quietly done."""
        from valuation.edge import track_meter as TM
        # The ANNUAL tracking error is what 2 and 6.5 fix at 11.40; sigma is DERIVED from it, so
        # the constant to pin is the input rather than the product.
        self.assertEqual(TM._TRACKING_ERROR_ANNUAL_PP, 11.40)
        self.assertAlmostEqual(TM.SIGMA_MONTHLY_PP, 3.9847, places=4)
        contract = _norm(_read(os.path.join(REPO, "PAPER_TRACK_CONTRACT.md")))
        self.assertIn("may never be revised downward", contract)
        self.assertIn("IS NOT REVISED", contract)

    def test_the_contract_still_states_the_rule_that_forbids_lowering_sigma(self):
        """The thing an edit would most plausibly have removed."""
        t = _read(os.path.join(REPO, "PAPER_TRACK_CONTRACT.md"))
        self.assertIn("may never be revised downward", t)

    def test_the_draft_is_KEPT_and_marked_ACCEPTED(self):
        """REPOINTED 2026-10-04. This asserted `NOTHING HERE IS IN FORCE`, which is now false of
        the file -- and it would have PASSED ANYWAY, because the amendment preserved that
        sentence inside a quotation of the original status line. That is the substring trap this
        record keeps paying for: a guard satisfied by prose ABOUT a rule rather than by the rule.
        So it asserts the status LINE's content positively, where a quotation cannot satisfy it.

        The draft is kept rather than deleted: an acceptance is only legible beside what was
        offered, and the figures must still be in it so the amendment's provenance is checkable
        from the proposal as well as from the contract."""
        p = os.path.join(REPO, "PREREG_DRAFT_contract_amendment_2.md")
        self.assertTrue(os.path.exists(p), "the amendment draft was deleted, not kept")
        t = _norm(_read(p))
        head = t[:t.index("---")] if "---" in t else t
        self.assertIn("ACCEPTED BY DON 2026-10-04", head)
        self.assertIn("IN FORCE AS AMENDMENT 2", head)
        self.assertNotIn("STATUS: DRAFT. NOTHING HERE IS IN FORCE.", head.split(">")[0],
                         "the live status line still declares the draft not in force")
        for n in ("9.9864", "1.9488", "8.4381", "4,383"):
            self.assertIn(n, t, "the draft lost %s" % n)

    def test_the_draft_does_not_propose_lowering_sigma(self):
        """The one thing the contract forbids outright."""
        t = _read(os.path.join(REPO, "PREREG_DRAFT_contract_amendment_2.md"))
        self.assertIn("may never be revised downward", t)
        self.assertIn("is NOT revised", t)

    def test_the_draft_states_the_amendment_makes_the_stated_power_WORSE(self):
        """A correction that only ever flattered would be the suspicious kind."""
        t = _read(os.path.join(REPO, "PREREG_DRAFT_contract_amendment_2.md"))
        self.assertIn("WORSE, not better", t)


class TheResearchDecileIsASeparateObject(unittest.TestCase):
    def test_the_two_blocks_share_no_return_key(self):
        """So a surface cannot render one under the other's label."""
        self.assertNotIn("net_pct", M.block())
        self.assertNotIn("roth", M.research_block())

    def test_the_research_block_says_it_is_not_the_index(self):
        self.assertIn("NOT the Valquo Index", M.research_block()["not_the_index"])
        self.assertIn("RESEARCH DECILE", M.research_block()["label"])

    def test_the_served_block_says_it_IS(self):
        self.assertIs(M.block()["is_the_served_book"], True)
        self.assertIs(M.research_block()["is_the_served_book"], False)


class TheDisclosureNamesAllThreeDifferences(unittest.TestCase):
    """`headline_scope` used to name the no-trade BAND and be silent on the UNIVERSE and the
    WEIGHTING, so the payload a user receives quoted all-cap equal-weighted figures for a
    large-cap score-weighted book. `INDEX-BOOK` reported it against this lane by name, and the
    band is the SMALLEST of the three: tier -5.9871pp, weighting +0.6804pp, band -0.8009pp.

    THE NEW FACTS ARE ADDITIVE. My first cut made `differs` mean "differs at all", and
    `test_no_trade_band` caught it: that field is the BAND question and two of its tests read
    it that way, so redefining it in place was the `provider` trap. `differs` is unchanged.
    """

    def _scope(self, *, banded=True, weighting="score", tier=1e10):
        import valuation.edge.valquo_index as V
        return V._headline_scope(0.30 if banded else None, weighting, tier)

    def test_differs_still_means_the_BAND_question(self):
        self.assertIs(self._scope(banded=True)["differs"], True)
        self.assertIs(self._scope(banded=False)["differs"], False)

    def test_the_universe_difference_is_reported_on_its_own_field(self):
        s = self._scope()
        self.assertIs(s["universe_differs"], True)
        self.assertIn("universe", " ".join(s["differs_on"]).lower())

    def test_the_weighting_difference_is_reported_on_its_own_field(self):
        s = self._scope()
        self.assertIs(s["weighting_differs"], True)
        self.assertIn("weighting", " ".join(s["differs_on"]).lower())

    def test_the_weighting_is_READ_and_not_assumed(self):
        """The first cut hard-coded "score-weighted", which is wrong for any caller passing
        `weighting="equal"` -- including `test_no_trade_band`'s own fixtures. A disclosure that
        misdescribes the book it discloses about is worse than none."""
        self.assertIs(self._scope(weighting="equal")["weighting_differs"], False)
        self.assertIs(self._scope(weighting="score")["weighting_differs"], True)

    def test_an_untiered_book_reports_no_universe_difference(self):
        self.assertIs(self._scope(tier=0.0)["universe_differs"], False)

    def test_it_still_names_the_band(self):
        """The old disclosure was incomplete, not wrong. Dropping it would be a regression,
        and `test_no_trade_band` pins the exact wording."""
        s = self._scope()
        self.assertIn("no-trade band", " ".join(s["differs_on"]))
        self.assertIn("WITHOUT a", s["note"])

    def test_the_note_says_the_band_is_NOT_the_largest_difference(self):
        self.assertIn("NOT THE LARGEST DIFFERENCE", self._scope()["note"])

    def test_the_decomposition_shows_the_band_is_the_smallest(self):
        d = self._scope()["one_knob_decomposition_pp_per_yr"]
        self.assertLess(abs(d["no_trade_band_0_to_030"]), abs(d["tier_all_cap_to_10bn"]))
        self.assertAlmostEqual(d["tier_all_cap_to_10bn"], -5.9871, places=4)

    def test_it_carries_the_served_measurement_rather_than_retyping_it(self):
        sv = self._scope()["served_book_measured"]
        self.assertIsNotNone(sv, "the disclosure lost the measured figures")
        self.assertEqual(sv["roth_pct"], M.SERVED_ROTH_PCT)
        self.assertEqual(sv["alpha_vs_all_cap_ew_pp"], M.ALPHA_VS_ALL_CAP_EW_PP)

    def test_the_served_figures_reach_the_note(self):
        self.assertIn("%.4f" % M.SERVED_ROTH_PCT, self._scope()["note"])


class E11ThePaperAccountsFairValueCopyIsConfirmed(unittest.TestCase):
    """E11 asked for the copy to be CONFIRMED, so it is checked against the code it describes.

    Three claims, all of them true, each pinned against `edge/positions.py` rather than read:

      * an ABSENT fair value cannot fire the exit  -> `fair_map.get(t) and ...` is falsy
      * the score floor is a SEPARATE route out    -> its own `elif` branch
      * there is no time limit on a hold           -> `paper_max_hold_days` is 0 and the branch
                                                      reads `if max_hold_days and ...`

    AND ONE IMPLICATION THAT WAS NOT TRUE, now corrected in the copy:
    `withhold_implausible_fair_values` fires only on `ratio > FV_BAND_HIGH` (5.0). A fair value
    that is implausibly LOW is warned about at `FV_BAND_LOW` (0.2) and NOT withheld, so it stays
    truthy and `price >= fair_value` holds at any real price. The old wording implied the guard
    was symmetric.
    """

    def test_an_absent_fair_value_cannot_fire_the_exit(self):
        import ast
        src = _read(os.path.join(REPO, "valuation", "edge", "positions.py"))
        fn = next(n for n in ast.walk(ast.parse(src))
                  if isinstance(n, ast.FunctionDef) and n.name == "update_positions")
        # ASSERTED IN PARTS, because `ast.unparse` NORMALISES: it renders the comparison as
        # `(price >= fair_map[...])` with parentheses the source does not have, so a one-literal
        # match fails against a correct tree. Same normalisation trap as the quote one this
        # project has already been caught by twice.
        body = ast.unparse(fn)
        self.assertIn("fair_map.get(p['ticker'])", body,
                      "the fair-value exit no longer guards on the value being present")
        self.assertIn("price >= fair_map[p['ticker']]", body)
        self.assertIn("'hit fair value'", body)
        # And the guard and the comparison are in ONE conjunction, not two statements where the
        # order could change.
        self.assertRegex(body, r"fair_map\.get\(p\['ticker'\]\)\s+and\s+\(?price >= ")

    def test_there_really_is_no_time_limit(self):
        from valuation.config import CONFIG
        self.assertEqual(getattr(CONFIG, "paper_max_hold_days", None), 0,
                         "the copy says there is no time limit on a hold")
        import ast
        src = _read(os.path.join(REPO, "valuation", "edge", "positions.py"))
        fn = next(n for n in ast.walk(ast.parse(src))
                  if isinstance(n, ast.FunctionDef) and n.name == "update_positions")
        self.assertIn("if max_hold_days and hold >= max_hold_days", ast.unparse(fn),
                      "a zero max_hold_days would no longer disable the time stop")

    def test_withholding_is_HIGH_side_only_and_the_copy_no_longer_implies_otherwise(self):
        from valuation.engine.publication import FV_BAND_HIGH, FV_BAND_LOW
        self.assertEqual(FV_BAND_HIGH, 5.0)
        self.assertEqual(FV_BAND_LOW, 0.2)
        import re
        src = _read(os.path.join(REPO, "valuation", "web", "static", "app.js"))
        src = re.sub(r"/\*.*?\*/", " ", src, flags=re.S)
        src = "\n".join(re.sub(r"//.*$", "", ln) for ln in src.splitlines())
        self.assertIn("implausibly <b>high</b>", src,
                      "the copy does not say the withholding is high-side only")
        self.assertNotIn("WITHHELD when neither can be computed", src,
                         "the old symmetric claim is still on the page")

    def test_the_exit_RULE_itself_is_untouched(self):
        """Changing it would change the paper account's recorded history, and the band is the
        engine lane's -- reported in the handoff, not altered here.

        Asserted as PROPERTIES of the three files rather than as a diff, for the reason in
        `test_the_SIGNED_contract_does_NOT_carry_the_correction`."""
        from valuation.engine.publication import FV_BAND_HIGH, FV_BAND_LOW
        self.assertEqual((FV_BAND_HIGH, FV_BAND_LOW), (5.0, 0.2),
                         "the bands moved; the copy describes them")
        wh = _read(os.path.join(REPO, "valuation", "web", "withhold.py"))
        self.assertIn("ratio <= band", wh,
                      "the withholding is no longer a one-sided high-side test")
        pos = _read(os.path.join(REPO, "valuation", "edge", "positions.py"))
        self.assertIn('reason = "hit fair value"', pos)
        self.assertIn("exit_score - exit_band", pos)


class TheDisclosureIsInertOnTheBook(unittest.TestCase):
    """Item 18 forbids changing how a rebalance book is BUILT. Proved against git rather than
    against my expectation, and with enough names that the comparison means something."""

    BOOK_FIELDS = ("positions", "n_positions", "n_eligible", "n_scored", "weighting",
                   "no_trade_band", "contract_conformance", "sector_weights",
                   "sector_data_available", "method", "weights")

    @staticmethod
    def _rows():
        out = []
        for i in range(400):
            out.append({"ticker": "T%03d" % i, "name": "Name %03d" % i,
                        "sector": ["Tech", "Health", "Fin", "Energy"][i % 4],
                        "market_cap": 2e9 + i * 1.2e9, "price": 10.0 + (i % 37),
                        "hot_score": 20.0 + (i * 0.19) % 75.0,
                        "score": 20.0 + (i * 0.19) % 75.0})
        out[0]["hot_score"] = out[0]["score"] = 99.9
        return out

    @classmethod
    def _build(cls):
        import valuation.edge.valquo_index as V
        importlib.reload(V)
        r = cls._rows()
        first = V.build_index(r, exit_frac=None)
        held = [p["ticker"] for p in first["positions"]][:20]
        return first, V.build_index(r, held=held, exit_frac=0.30)

    def test_the_book_is_identical_against_the_pre_change_source(self):
        base = subprocess.run(["git", "show", "origin/main:valuation/edge/valquo_index.py"],
                              cwd=REPO, capture_output=True)
        if base.returncode != 0 or not base.stdout:
            self.skipTest("origin/main copy of valquo_index.py unavailable")
        with io.open(VI, "rb") as _f:
            cur = _f.read()
        # NORMALISE BEFORE COMPARING, AND THAT IS A DEFECT IN THIS TEST'S FIRST CUT.
        #
        # `git show` emits LF; the working tree on this machine is CRLF. So `base.stdout ==
        # cur` was NEVER equal, the "nothing to prove" skip could not fire, and the moment the
        # change landed on origin/main the two sources became content-identical and the final
        # "the disclosure DID move" assertion failed -- a red suite reporting that a landed,
        # correct change had done nothing.
        #
        # The recorded version of this trap is about DECODING a git baseline as cp1252; this is
        # the same family one step along: comparing a git baseline's BYTES against a working
        # tree whose line endings the checkout chose. Compare content, not bytes.
        def _norm(b):
            return b.decode("utf-8", "replace").replace("\r\n", "\n")
        if _norm(base.stdout) == _norm(cur):
            # LOUD, not silent. Once this change is on main this test can only ever skip, and
            # a quiet skip reads as a pass.
            print("       (ALREADY LANDED: valquo_index.py matches origin/main, so the "
                  "one-time inertness demonstration has nothing to compare. The BOOK-identity "
                  "assertions below are what keep standing.)")
            self.skipTest("the file is content-identical to origin/main; nothing to prove")

        a_first, a_band = self._build()
        with io.open(VI, "wb") as _f:
            _f.write(base.stdout)
        try:
            b_first, b_band = self._build()
        finally:
            with io.open(VI, "wb") as _f:
                _f.write(cur)
            importlib.reload(importlib.import_module("valuation.edge.valquo_index"))
        with io.open(VI, "rb") as _f:
            self.assertEqual(_f.read(), cur, "restore failed")

        # REACH, asserted and not assumed.
        self.assertGreaterEqual(a_first.get("n_eligible") or 0, 100)
        self.assertGreaterEqual(a_first.get("n_positions") or 0, 10)
        self.assertIs((a_band.get("no_trade_band") or {}).get("applied"), True)

        moved = []
        for k in self.BOOK_FIELDS:
            for lbl, x, y in (("no-band", b_first, a_first), ("band", b_band, a_band)):
                if (json.dumps(x.get(k), sort_keys=True, default=str)
                        != json.dumps(y.get(k), sort_keys=True, default=str)):
                    moved.append("%s/%s" % (lbl, k))
        self.assertEqual(moved, [], "the build changed: %r" % (moved,))

        # And the disclosure DID move, or the change did nothing.
        #
        # REPOINTED 2026-10-04 (`INDEX-CANDIDATE`), and the guard fired on the first unrelated
        # edit to this file -- which is what forced the repoint rather than any judgement about
        # whether it is worth having.
        #
        # THE DEFECT: the skip above is keyed on "this file is content-identical to
        # origin/main", used as a proxy for "the disclosure change is still pending". Once that
        # change landed, the proxy inverted: ANY subsequent edit to `valquo_index.py` re-arms
        # the test, and it then demands that the edit move `headline_scope`. A universe-trim
        # helper and a candidate registry do not touch the disclosure, so a correct, inert
        # change came back red with a message saying it "did nothing". That is the family this
        # record names twice -- `MA4`'s guard keyed on a property of the LAYOUT, and `MB31`'s
        # tripwire asserting "these two numbers are equal today", which fires on the CLOCK.
        #
        # THE REPOINT KEEPS EVERY ASSERTION AND MOVES ONLY WHAT DECIDES WHETHER THEY APPLY. The
        # book-inertness check above has ALREADY RUN against origin/main's own source by the
        # time we get here, which is the valuable half and now runs on every edit rather than
        # only on a disclosure edit. What is conditional is the DISCLOSURE half, and it is
        # conditional on the thing it is about: if `headline_scope` did not move, this edit is
        # not a disclosure edit and the one-time demonstration has nothing to demonstrate. It
        # skips LOUDLY with that reason, because a silent skip reads as a pass.
        _a = json.dumps(a_first.get("headline_scope"), sort_keys=True, default=str)
        _b = json.dumps(b_first.get("headline_scope"), sort_keys=True, default=str)
        if _a == _b:
            print("       (this edit does not touch `headline_scope`, so the one-time "
                  "disclosure demonstration has nothing to show. The BOOK-INERTNESS assertion "
                  "above DID run against origin/main's own source and passed.)")
            self.skipTest("the edit under test is not a disclosure change; book inertness "
                          "was asserted above")
        self.assertNotEqual(_b, _a)


if __name__ == "__main__":
    unittest.main(verbosity=2)
